sources:
  oracle:
    type: cdc
    logging:
      level: debug
    connection:
      type: oracle
      host: localhost
      port: 1521
      user: c##dbzuser
      password: dbz
    advanced:
      source:
        database.dbname: ORCLCDB
        database.pdb.name: ORCLPDB1
        decimal.handling.mode: precise
        value.converter.schemas.enable: true
        key.converter.schemas.enable: true
processors:
  target_data_type: json
targets:
  target:
    connection:
      type: redis
      host: localhost
      port: 12000
      password: secret42
