sources:
  oracle:
    type: cdc
    logging:
      level: info
    connection:
      type: oracle
      host: 192.168.20.3
      port: 1521
      user: c##dbzuser
      password: dbz
    advanced:
      source: 
        database.dbname: ORCLCDB
        database.pdb.name: ORCLPDB1
        decimal.handling.mode: precise
        value.converter.schemas.enable: true
        key.converter.schemas.enable: true
processors:
  target_data_type: json
targets:
  target:
    connection:
      type: redis
      host: 192.168.20.2
      port: 12000