title = "RDI Silent Installer Config"

scaffold = false
db_index = 5
deploy_directory = "/opt/rdi/config"
deploy = true

[rdi.database]
host = "192.168.20.2"
port = 12001
use_existing_rdi = true
password = "redis"