networks:
  rdi-net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

services:
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - 12000:12000
      - 12001:12001
      - 8443:8443
      - 9443:9443
    volumes:
      - $PWD/redis-cli/scenarios:/opt/scenarios
    networks:
      rdi-net:
        ipv4_address: 192.168.20.2

  oracle:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle
    ports:
     - 1521
    environment:
     - ORACLE_SID=ORCLCDB 
     - ORACLE_EDITION=enterprise
     - ORACLE_PWD=Password1
     - INIT_SGA_SIZE=1616M
     - INIT_PGA_SIZE=1616M
    volumes:
      - $PWD/oracle/scripts:/opt/oracle/scripts/startup
      - $PWD/sqlplus/scenarios:/opt/scenarios
    healthcheck:
      test: /opt/oracle/checkDBStatus.sh
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 10m
      start_interval: 30s
    networks:
      rdi-net:
        ipv4_address: 192.168.20.3

  rdi:
    build: 
      context: $PWD/rdi
    container_name: rdi
    privileged: true
    restart: on-failure
    depends_on:
      re1:
        condition: service_started
      oracle:
        condition: service_healthy
    networks:
      rdi-net:
        ipv4_address: 192.168.20.4